/**
 * stm32_main.c — STM32H7 firmware entry point
 *
 * Initialisation order (Phase 0 stubs):
 *   1. SystemClock_Config  → 480 MHz
 *   2. HAL peripherals     → LTDC, DMA2D, SAI/I2S, USB HS, GPIO matrix
 *   3. lv_init + hal_display_init
 *   4. app_main_init       → creates FreeRTOS tasks
 *   5. vTaskStartScheduler
 */

/* STM32 HAL (generated by STM32CubeMX — add to project when hardware is ready) */
/* #include "stm32h7xx_hal.h" */

#include "lvgl.h"
#include "hal.h"
#include "app_main.h"

/* FreeRTOS */
#include "FreeRTOS.h"
#include "task.h"

/* ── Tick ────────────────────────────────────────────────────────────────── */
uint32_t hal_tick_ms(void) {
    /* On STM32: HAL_GetTick() returns ms since boot (driven by SysTick) */
    /* return HAL_GetTick(); */
    return 0;   /* stub */
}

void hal_delay_ms(uint32_t ms) {
    vTaskDelay(pdMS_TO_TICKS(ms));
}

/* ── Display ─────────────────────────────────────────────────────────────── */
void hal_display_init(void) {
    /* TODO Phase 0 STM32:
     *   - Initialise LTDC for 800×480 RGB parallel
     *   - Configure DMA2D for colour fill and ARGB8888 blending
     *   - Register LVGL display driver pointing at LTDC framebuffer
     * Implemented in stm32_hal_impl.c */
}

/* ── Task management ─────────────────────────────────────────────────────── */
void hal_task_create(hal_task_fn_t fn, const char *name,
                     uint32_t stack_bytes, void *arg, int priority) {
    xTaskCreate((TaskFunction_t)fn, name,
                stack_bytes / sizeof(StackType_t),
                arg, (UBaseType_t)priority, NULL);
}

void hal_task_delay_ms(uint32_t ms) {
    vTaskDelay(pdMS_TO_TICKS(ms));
}

/* ── FreeRTOS hooks ──────────────────────────────────────────────────────── */
void vApplicationMallocFailedHook(void) {
    /* Replace with hardware assert / watchdog reset */
    for (;;) {}
}

void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName) {
    (void)xTask; (void)pcTaskName;
    for (;;) {}
}

/* ── Entry point ─────────────────────────────────────────────────────────── */
int main(void) {
    /* HAL_Init(); */
    /* SystemClock_Config(); */

    lv_init();
    lv_tick_set_cb(hal_tick_ms);

    hal_display_init();
    app_main_init();

    vTaskStartScheduler();

    /* Should never reach here */
    for (;;) {}
}
